<a href="https://colab.research.google.com/github/Ezhil-Adhithya/Pytorch-Tutorial/blob/main/pytorch%20basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch

NUMPY

In [1]:
import numpy as np
x=np.random.rand(3,4)
x

array([[0.02817339, 0.40705657, 0.906186  , 0.31789895],
       [0.19663815, 0.51456069, 0.89952133, 0.63080702],
       [0.08559151, 0.39127989, 0.96265621, 0.4541655 ]])

In [2]:
x.dtype

dtype('float64')

**TENSORS**

In [8]:
tensor_2d=torch.rand(3,4)
tensor_2d

tensor([[0.4351, 0.3635, 0.1761, 0.7994],
        [0.9055, 0.2700, 0.8582, 0.7171],
        [0.9903, 0.2125, 0.5990, 0.2386]])

In [9]:
tensor_3d=torch.rand(2,3,4)
tensor_3d

tensor([[[0.2181, 0.6918, 0.0033, 0.4227],
         [0.8023, 0.8572, 0.0723, 0.8456],
         [0.3724, 0.7239, 0.2613, 0.9963]],

        [[0.3455, 0.6930, 0.7695, 0.8796],
         [0.1347, 0.4262, 0.9615, 0.5197],
         [0.5081, 0.2309, 0.4234, 0.6485]]])

In [11]:
torch.tensor(x)

tensor([[0.0282, 0.4071, 0.9062, 0.3179],
        [0.1966, 0.5146, 0.8995, 0.6308],
        [0.0856, 0.3913, 0.9627, 0.4542]], dtype=torch.float64)

In [12]:
my_torch=torch.arange(10)

In [13]:
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# reshape
my_torch.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
t=torch.arange(10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
t2=t.reshape(5,2)
t2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [27]:
t2[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [28]:
a=torch.tensor([1,2,3,4])
b=torch.tensor([5,6,7,8])

In [29]:
torch.add(a,b)

tensor([ 6,  8, 10, 12])

In [30]:
torch.sub(a,b)

tensor([-4, -4, -4, -4])

In [31]:
torch.mul(a,b)

tensor([ 5, 12, 21, 32])

In [32]:
torch.div(a,b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [34]:
torch.remainder(b,a)

tensor([0, 0, 1, 0])

In [35]:
# power of
torch.pow(a,b)

tensor([    1,    64,  2187, 65536])